1) Ejecutar el primer paso en el navegador
http://localhost:8080/h2-console/login.jsp

2) Cargar los datos por defectos y consultas.
INSERT INTO CLIENTE (CIUDAD,DIRECCION,NOMBRE,TELEFONO) VALUES('BARRANQUILLA','CARRERA 16C # 45F-08','GEOVANNY',3114268610);
INSERT INTO CLIENTE (CIUDAD,DIRECCION,NOMBRE,TELEFONO) VALUES('LA PAZ','CARRERA 16C # 45F-08','KETTY',3114268610);
INSERT INTO TARJETA (CCV,NUMTARJETA,TIPTARJETA,ID_CLIENTE) VALUES(123,1234567890987654,'CREDITO',1);
INSERT INTO TARJETA (CCV,NUMTARJETA,TIPTARJETA,ID_CLIENTE) VALUES(111,8765432190987654,'DEBITO',1);
INSERT INTO DETALLE_CONSUMO(DESCRIPCION,FECHA,MONTO,ID_TARJETA) VALUES('COMPRA PAYPAL','2019-02-05',20000,1);
INSERT INTO DETALLE_CONSUMO(DESCRIPCION,FECHA,MONTO,ID_TARJETA) VALUES('COMPRA IBM','2019-02-05',45000,1);
INSERT INTO ASESOR (NOMBRE,ESPECIALIDAD) VALUES ('EUGENIA','COMERCIAL');
INSERT INTO ASESOR (NOMBRE,ESPECIALIDAD) VALUES ('CLAUDIA','CAJERA');

SELECT * FROM CLIENTE;
SELECT * FROM TARJETA;
SELECT * FROM DETALLE_CONSUMO;

SELECT C.NOMBRE, C.DIRECCION, C.CIUDAD, C.TELEFONO,T.NUMTARJETA,T.CCV, T.TIPTARJETA, D.FECHA,D.DESCRIPCION,D.MONTO 
FROM CLIENTE C, TARJETA T, DETALLE_CONSUMO D
WHERE C.ID_CLIENTE=T.ID_CLIENTE
AND T.ID_TARJETA=D.ID_TARJETA